### ISSUE TITLE
Migrate Paperclip to ActiveStorage

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/Farmbot-Web-App#1287]
Paperclip is now deprecated.

The migration guide is available [here](https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md).

# TODO:

 - [x] Install `ActiveStorage`
 - [x] Store images to ActiveStorage via local filesystem
 - [X] Store images to ActiveStorage via GCS
 - [X] Deprecate old image uploader.

# Questions

 * How will this affect [legacy] FBOS image uploads?
 * How will we handle self-hosted / non-GCS setups?
