### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1330]
Ability to define Groups of plants with criteria and/or manual selection, and then being able to use the Groups in Sequences/Variables.

Mockup shows some various design ideas and possible criteria, as well as suggested changes to the select plants mode to accommodate creating groups via box selection.

[Groups Mockup.pdf](https://github.com/FarmBot/Farmbot-Web-App/files/3424860/Groups.pdf)

### Bare minimum implementation (as seen in the two right-most mockups in the PDF)

- [x] Groups endpoint
- [x] Groups panel (list all groups, `+` button)
- [x] Edit group panel (group name, group members, delete button, save button)
- [x] Ability to manually edit plants in group (click to add/remove) when edit group panel is opened
- [x] Add `CREATE GROUP` button to box-select panel
- [x] Search filter
- [x] Ability to edit and save group name
- [x] "GROUP NAME" and "GROUP MEMBERS (2)" should be classed `label` instead of `h5`
- [x] Add `padding: 0.5em 0em` to the div that is holding all the group member plant icons
- [x] Update groups list padding: What is currently classed as `plant-search-item-age`, change padding-top to `0.6rem` and probably change the class name to something like `group-item-count` so as to not mess up styling on the plants list.
- [x] Add empty-state graphic for when the user has no groups. [Graphic](https://user-images.githubusercontent.com/5524043/64480191-352e0580-d178-11e9-90e5-aff925032639.png)
- [x] Remove `every_*` options in favor of a future criteria-based-auto-group
- [x] Add **SORT BY** dropdown to the edit group panel (in between the group name and group members sections) with options: `X/Y Ascending`, `X/Y Descending`, `Y/X Ascending`, `Y/X Descending`, `Random`. Add a tooltip next to the **SORT BY** label with the following help text: "When executing a sequence over a Group of locations, FarmBot will travel to each group member in the order of the chosen sort method. If the random option is chosen, FarmBot will travel in a random order every time, so the ordering shown below will only be representative."
- [x] Add dependency tracking for groups that are in-use by a sequence, regimen, or event
- [x] Update colors:
- [x] `float: left` the `DELETE GROUP` button, and give it `margin-top: 1em`
- [x] Panel nav background to `#026365` (slight typo currently)
- [x] Panel background to `#f0f8f8`
- [x] Group list item background hover to `#d7eaea`
- [x] `+` button background to `#026365`
- [x] `+` button background hover color to `#025758`
- [x] `+` button bottom border to `#013738`

**Comment by RickCarlino** [comment]
Ideas: Name criteria based groups "dynamic groups" and call the other kind just "group" or "standard group".

Backend TODO items for this one:

 - [ ] Create `/api/point_groups` endpoint.
 - [ ] Create `/api/point_group_item` endpoint
 - [ ] Add bulk endpoint for `PointGroupItem::Create`.

Schema (pseudocode):

```typescript
interface PointGroup {
  id?: Date;
  created_at?: Date;
  name?: string;
}

interface PointGroupItem {
  id?: Date;
  created_at?: Date;
  point_group_id: number;
  point_id: number;
}

interface Point {
  /** This already exists. See FarmBotJS */
}
```

**Comment by RickCarlino** [comment]
![image](https://user-images.githubusercontent.com/1388608/62544064-b6664580-b824-11e9-8039-c74561f5a383.png)
For reference, I am copying an image version of the mockup in the PDF.

**Comment by RickCarlino** [comment]
![image](https://user-images.githubusercontent.com/1388608/62561891-b62a7200-b845-11e9-92cf-fa70e0aa9f53.png)

**Comment by RickCarlino** [comment]
Adding this here for reference:

![image](https://user-images.githubusercontent.com/1388608/71745537-024b0400-2e30-11ea-8861-f979713353e8.png)

![image](https://user-images.githubusercontent.com/1388608/71745556-10992000-2e30-11ea-929e-1661a70fec76.png)
