### ISSUE TITLE
Implement Turnkey Sequences on Device Table

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/Farmbot-Web-App#1447]
Sometimes, you need a sequence to execute every time the device boots. By adding a `turnkey_sequence_id` column to the `device` record, FBOS will have the information it needs to run such a sequence.

# TODO

 - [ ] Add `turnkey_sequence_id` to device table
 - [ ] Add ability to change said column via API
 - [ ] Prevent deletion of turnkey sequences (will need special message).
 - [ ] Add dropdown panel to device page
