### ISSUE TITLE
Miscellaneous Usability Improvements

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#2089]
In the process of making the new video I had to use the app quite a bit to make some nice garden layouts and set up the bot to do what I needed it to do on camera. Here is a list of things that I noticed (in no particular order) that were slowing me down from a workflow perspective, some of which we have issues for and others not.

- [x] Have to go into the settings panel to SET HOME or FIND HOME (#1517)
- [x] Have to go into the controls gear menu to know if a bot is going to go to home or find home when pressing the home button (#1516)
- [ ] Want to be able to select a group as a default variable value for more quickly using the RUN button, or scheduling it in an event, or using it via EXECUTE. You can select a group from the run button 1-time-variable-selection menu, which is nice.
- [ ] Desired user configurable landing page (#1461)
- [ ] Desired more efficient group sort orders for watering and taking photos
- [x] Desired ability to bulk edit plant radii, coordinates, and start dates
- [x] [Bug] Can't delete all digits from grid planting fields (#1979)
- [ ] No ability to describe saved gardens other than with titles (#1571)
- [x] Long garden titles are not well supported in the gardens list. (#1978)
- [ ] Would like to change the crop type of a plant
- [ ] Wanted to just drag plants around, rather than having to first select one and then click and drag.
- [x] There should be a button in the gardens panel to delete all current plants so you can quickly apply a different garden without having to leave the panel to delete and then come back.
- [x] Separate add to map and crop details panels seem unnecessary and slows down the workflow of creating a new garden
- [x] Arrow keys to move plants around when selected would be really nice
- [x] Combining the plants, groups, and gardens inventory panels into one panel with collapsible accordion sections (like the weeds panel) would make sense and help with navigation. Groups would maybe need a FE rework to handle groups of plants, points, or weeds well.
- [x] Warning icon should be taken off the group filters feature
- [x] Controls popup feels much less useful with the consolidation into the farm designer. It could either use more features (home button, distance selector, etc) or it may be worth removing?
- [ ] Spread and current size indicators get cut off for larger plants at the ends of the bed
- [ ] No indication in farm designer when bot is finding home (or axis length)
- [x] The map menu feels bloated (#1499)

### Other random UI/X improvements and small feature ideas
- [x] Changing color or radius should live-update the point grid preview
- [ ] Add sequence copy and delete buttons to 3-dot menu in sequence list panel
- [ ] Activity beeps account setting
- [ ] Remove AUTO UPDATE toggle and add a new option for "Never" to the UPDATE TIME dropdown. Surviving label should be AUTO UPDATE
